services:
  - type: static
    name: bric-tournament-analysis
    env: static
    buildCommand: echo "Ready to deploy"
    staticPublishPath: .
    routes:
      - path: /*
        methods:
          - GET
        dest: /index.html
